### ISSUE TITLE
Use SPA server to serve the app in docker

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/element#101]
https://www.npmjs.com/package/http-server-spa
https://github.com/decentralized-identity/element/blob/dae889f0a6c74535f57ff623ed7c2df7691fb027/packages/element-app/package.json#L54

**Comment by OR13** [comment]
I think what we really want here is a single docker image which ships the server and the pwa code, and handles pathing properly.

**Comment by gjgd** [comment]
What do you mean by "handles pathing properly"?

**Comment by OR13** [comment]
https://github.com/lwsjs/local-web-server/wiki/How-to-serve-a-Single-Page-Application-(SPA)

**Comment by OR13** [comment]
test any PWA by going to a route like `/example/123/456`... and hitting force refresh... if you get a 404, you know the web server is not configured correctly.

**Comment by OR13** [comment]
See also: https://firebase.google.com/docs/hosting/full-config#rewrites which are used in the app today.

**Comment by gjgd** [comment]
Ah yes, I see good point
