### ISSUE TITLE
Universal resolver example fails

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/element#130]
https://uniresolver.io/#did:elem:sscP2_bGvj2z6qnSV68ja-WR8WKCLTvNoRJjYSBvDZs

**Comment by peacekeeper** [comment]
This DID seems to fail here as well: https://element-did.com/server/resolver

Should it resolve? Maybe it's outdated? I can easily replace the UR example with something else.

**Comment by gjgd** [comment]
Yes, we published some breaking changes to re-align with the Sidetree protocol that invalidated old dids.
This is a working example: https://uniresolver.io/#did:elem:EiB9htZdL3stukrklAnJ0hrWuCdXwR27TNDO7Fh9HGWDGg

**Comment by gjgd** [comment]
https://github.com/decentralized-identity/universal-resolver-frontend/pull/9
https://github.com/decentralized-identity/universal-resolver/pull/70

**Comment by peacekeeper** [comment]
Thankes, merged both PRs.
