### ISSUE TITLE
Fix warnings in element-app

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/element#158]
<img width="1440" alt="Screenshot 2020-01-23 at 16 07 54" src="https://user-images.githubusercontent.com/7913565/72970612-9b9b8380-3dfa-11ea-91d4-9735401e0205.png">

<img width="1440" alt="Screenshot 2020-01-23 at 15 43 01" src="https://user-images.githubusercontent.com/7913565/72970613-9c341a00-3dfa-11ea-9541-348432b61e14.png">

**Comment by OR13** [comment]
I think this is now fixed

**Comment by gjgd** [comment]
All good!
