### ISSUE TITLE
PoisonedOperationAttack test is failing

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/element#37]
https://travis-ci.org/decentralized-identity/element/builds/555983150#L677

`expect(op.consideredUnresolvableUntil).toBeDefined();` is false, but the test still shows as passing

**Comment by OR13** [comment]
yes, this is a type error probably... if its defined its true.

The idea is that when bad data is detected the local cache mutates the data marking it as such, same thing happens for anchorFile and batchFile data.

The idea with the test should be to show that a poisoned operation is marked as consideredUnresolvableUntil.

**Comment by gjgd** [comment]
Understood! Then this test should be fixed because consideredUnresolvableUntil is not defined after the db read
