### ISSUE TITLE
Element Failing to build on AWS EC2 (t2.micro). ErrorNo: 137

### ISSUE THREAD

**Issue by adityaishan** [decentralized-identity/element#42]
I have already build element locally on my PC.
I am trying to build on AWS EC2 too. 
Specs i am using are: t2.micro:1GB ram and storage of 8 GB.

Command: npm i //ran perfectly
Command npm run services:start //Failing and its killing the contracts.
                                    
ubuntu@ip:~/decentralized-identity/element$ sudo npm run services:start

> @transmute/element@ services:start /home/ubuntu/decentralized-identity/element
> lerna run services:start --stream

lerna notice cli v3.15.0
lerna info Executing command in 1 package: "npm run services:start"
@transmute/element-lib: > @transmute/element-lib@0.0.2-2 services:start /home/ubuntu/decentralized-identity/element/packages/element-lib
@transmute/element-lib: > ./scripts/start_services.sh
@transmute/element-lib: 🧙 Starting Element Services...
@transmute/element-lib: ✨ Starting GANACHE on 8545
@transmute/element-lib: > @transmute/element-lib@0.0.2-2 contracts:migrate:dev /home/ubuntu/decentralized-identity/element/packages/element-lib
@transmute/element-lib: > truffle migrate --network development --reset
@transmute/element-lib: Compiling your contracts...
@transmute/element-lib: ===========================
@transmute/element-lib: Killed
@transmute/element-lib: npm ERR! code ELIFECYCLE
@transmute/element-lib: npm ERR! errno 137
@transmute/element-lib: npm ERR! @transmute/element-lib@0.0.2-2 contracts:migrate:dev: `truffle migrate --network development --reset`
@transmute/element-lib: npm ERR! Exit status 137
@transmute/element-lib: npm ERR! 
@transmute/element-lib: npm ERR! Failed at the @transmute/element-lib@0.0.2-2 contracts:migrate:dev script.
@transmute/element-lib: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@transmute/element-lib: npm ERR! A complete log of this run can be found in:
@transmute/element-lib: npm ERR!     /home/ubuntu/.npm/_logs/2019-07-30T06_18_24_902Z-debug.log
@transmute/element-lib: lerna notice cli v3.15.0
@transmute/element-lib: lerna info Executing command in 1 package: "npm run env:create:local"
@transmute/element-lib: @transmute/element-api: > @transmute/element-api@0.0.2-2 env:create:local /home/ubuntu/decentralized-identity/element/packages/element-api
@transmute/element-lib: @transmute/element-api: > node ./scripts/env_to_json_config.js local ../../example.env ./local.runtimeconfig.json && ./scripts/update_runtimeconfig_contract.sh ./local.runtimeconfig.json
@transmute/element-lib: @transmute/element-api: 👷 Modifying  ./local.runtimeconfig.json
@transmute/element-lib: @transmute/element-api: ✅ element.ethereum.anchor_contract_address:  0x1DABA81D326Ae274d5b18111440a05cD9581b305
@transmute/element-lib: lerna success run Ran npm script 'env:create:local' in 1 package in 0.7s:
@transmute/element-lib: lerna success - @transmute/element-api
@transmute/element-lib: /home/ubuntu/decentralized-identity/element/packages/element-lib
@transmute/element-lib: ✨ Starting IPFS on 5001
lerna success run Ran npm script 'services:start' in 1 package in 16.2s:
lerna success - @transmute/element-lib

**Comment by OR13** [comment]
Hmm, you probably don't need sudo if node is installed correctly, maybe checkout nvm. I'm not sure that is the issue though.

can you paste your node version information?

```
node -v 
```

**Comment by adityaishan** [comment]
@OR13 
node: 10.16.0 
Npm: 6.10.2

From what I came across on online sources that error no 137 shows up due to low memory. Can you suggest how much memory would be sufficient to run element on EC2 instance or the minimum hardware specs. needed for element.

**Comment by gjgd** [comment]
@adityaishan thanks for reporting.
I was able to reproduce the error on a t2.micro and it does seem like there are not enough RAM.

I tried using a t2.small which has 2GB instead of 1GB of RAM and was able to run the project, therefore I'm closing this for now but feel free to reopen if the issue persists on a t2.small for you

**Comment by adityaishan** [comment]
Thanks for the update.
