### ISSUE TITLE
Cannot find "@transmute/element-core" after "npm run test"

### ISSUE THREAD

**Issue by adityaishan** [decentralized-identity/element#53]
After running,  
> npm run test

The test suit is failing.

> @transmute/element-modules: FAIL src/Node/ElementCore.Node.spec.js
> @transmute/element-modules:   ● Test suite failed to run
> @transmute/element-modules:     Cannot find module '@transmute/element-core' from 'ElementCore.Node.spec.js'
> @transmute/element-modules:     > 1 | const ElementCore = require("@transmute/element-core");
> @transmute/element-modules:         |                     ^
> @transmute/element-modules:       2 | 
> @transmute/element-modules:       3 | describe("ElementCore", () => {
> @transmute/element-modules:       4 |   describe("MnemonicKeySystem", () => {
> @transmute/element-modules:       at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:230:17)
> @transmute/element-modules:       at Object.require (src/Node/ElementCore.Node.spec.js:1:21)
> @transmute/element-modules: Test Suites: 1 failed, 1 total
> @transmute/element-modules: Tests:       0 total
> @transmute/element-modules: Snapshots:   0 total
> @transmute/element-modules: Time:        0.951s
> @transmute/element-modules: Ran all test suites.
 
Even i change the path to _"home/adityaishan/decentralized-identity/element/packages/element-modules/node_modules/@transmute/element-core"_, the test is still failing.

**Comment by gjgd** [comment]
This looks related to linking. Have you run `npm install` in the root directory?

**Comment by adityaishan** [comment]
Got it, need go to _packages/element-core_ and then build it first before running the test suits.

**Comment by gjgd** [comment]
Thanks for reporting! This issue will be solved in #57, you'll be able to run `npm run test` after `npm install` without having to build element-core
