### ISSUE TITLE
Add element to Universal Resolver

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/element#6]
- https://github.com/decentralized-identity/universal-resolver

Once the method stabilizes a bit more.

**Comment by OR13** [comment]
Blocked by https://github.com/decentralized-identity/element/issues/33

**Comment by OR13** [comment]
Unblocked, https://github.com/decentralized-identity/universal-resolver/issues/41

**Comment by gjgd** [comment]
done in https://github.com/decentralized-identity/universal-resolver/pull/45
